mesela dinamik modellerde uzayımız değişir mi? Değişedebilir...

integer problemleri çözmek daha zordur.

sdm için;
deterministic bir yapı aslında. 

malzeme akışı, bilgi akışı ve para akışı hızlı ve yeterliyse, tedarik zinciri daha başarılı oluyor. 

In [2]:
import numpy as np
import pandas as pd

In [9]:
A=np.array([[1,1,2],[2,1,3]]); B=np.array([[1,1],[2,3],[1,2]])

In [10]:
A

array([[1, 1, 2],
       [2, 1, 3]])

In [11]:
B

array([[1, 1],
       [2, 3],
       [1, 2]])

In [12]:
C=A.dot(B)

In [13]:
C

array([[ 5,  8],
       [ 7, 11]])

In [15]:
np.matmul(A,B)

array([[ 5,  8],
       [ 7, 11]])

In [16]:
def matris_carpım (a,b):
    matris_carpım=a.dot(b)
    return(matris_carpım)

In [18]:
matris_carpım(A,B)

array([[ 5,  8],
       [ 7, 11]])

In [34]:
A=np.array([[3],[4]])
B=np.array([[1,2]])

In [36]:
matris_carpım(A,B)

array([[3, 6],
       [4, 8]])

class nedir?

Bir obje var. O objenin metotları, tanımı, özellikleri, vb. bunları tutuyor. 

#LEGB önemli!!!

In [40]:
matris_carpım(B,A)

array([[11]])

In [43]:
C=np.array([[1,2],[3,4]]); D=np.array([[1,1],[0,1],[1,2]])

In [44]:
matris_carpım(C,D)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [45]:
G=np.array([[3/4,2/3,1/4],[1/4,1/3,3/4]])

In [47]:
pd.DataFrame(G)

0         1     2
0  0.75  0.666667  0.25
1  0.25  0.333333  0.75

In [48]:
C=np.array([[10],[6],[5]])

In [52]:
matris_carpım(G,C)

array([[12.75],
       [ 8.25]])

In [53]:
W= np.array([[1,1,2],[2,1,3]])
Z= np.array([[1,1],[2,3],[1,2]])

In [55]:
matris_carpım(W,Z)

array([[ 5,  8],
       [ 7, 11]])

In [62]:
matris_carpım(W[0],Z)

array([5, 8])

In [57]:
matris_carpım(W[1],Z)

array([ 7, 11])

In [59]:
matris_carpım(W,Z)[0]==matris_carpım(W[0],Z)

array([ True,  True])

In [60]:
matris_carpım(W,Z)[1]

array([ 7, 11])

In [61]:
matris_carpım(W,Z)[1]==matris_carpım(W[1],Z)

array([ True,  True])

In [71]:
matris_carpım(W[0:1],Z[1])

ValueError: shapes (1,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

In [75]:
Z[:,0]

array([1, 2, 1])

In [77]:
Z

array([[1, 1],
       [2, 3],
       [1, 2]])

In [79]:
matris_carpım(W,Z[:,0])

array([5, 7])

In [83]:
matris_carpım(W,Z)[:,0]

array([5, 7])

In [84]:
L=np.array([[2],[1]])

In [85]:
L

array([[2],
       [1]])

In [90]:
matris_carpım(matris_carpım(W,Z),L)

array([[18],
       [25]])

In [94]:
matris_carpım(W,matris_carpım(Z,L))

array([[18],
       [25]])