
# Modellemeye Giriş









Yön-eylem araştırması (operations research)

Matematiksel modellemenin çıktısı formüldür.

Matematiksel model açıklayıcı olarak kullanılır.

Matematiksel modelleme:
      - Açıklayıcı (istatistik, EDA kullanılır)
      - Tahmin (ML)
      - Tanımlayıcı (Optimizasyon - objective - decision variables - constraints)
      
      

1 Şubat 2020 2. Hafta

Temel Lineer Cebir



In [5]:
import numpy as np
import pandas as pd

In [8]:
A=np.array([[1,1,2],[2,1,3]])
B=np.array([[1,1],[2,3],[1,2]])


In [19]:
A

array([[1, 1, 2],
       [2, 1, 3]])

In [20]:
B

array([[1, 1],
       [2, 3],
       [1, 2]])

In [10]:
A.dot(B)

array([[ 5,  8],
       [ 7, 11]])

In [11]:
A.shape


(2, 3)

In [12]:
B.shape

(3, 2)

In [26]:
A=np.array([[3],[4]])
B=np.array([[1,2]])

In [41]:
def matris_carpimi(a,b):
    d=a.dot(b)
    return(d)
    

In [28]:
matris_carpimi(A,B)

array([[3, 6],
       [4, 8]])

In [30]:
matris_carpimi(B,A)

array([[11]])

In [31]:
C=np.array([[1,2],[3,4]])
D=np.array([[1,1],[0,1],[1,2]])

In [32]:
matris_carpimi(C,D)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [34]:
c=np.array([[c1,c2]])


NameError: name 'c1' is not defined

In [35]:
x=np.array([[3/4,2/3,1/4],[1/4,1/3,3/4]])
y=np.array([[pu],[ru],[rl]])

NameError: name 'pu' is not defined

In [36]:
E=np.array([[1,1,2],[2,1,3]])
F=np.array([[1,1],[2,3],[1,2]])

In [47]:
matris_carpimi(E,F)

array([[ 5,  8],
       [ 7, 11]])

In [42]:
matris_carpimi(E[0],F)

array([5, 8])

In [49]:
matris_carpimi(E,F[:,1])


array([ 8, 11])

In [53]:
G=np.array([[1,2]])
H=np.array([[2,3],[4,5]])
I=np.array([[2],[1]])

In [54]:
a=matris_carpimi(H,I)

In [57]:
G.dot(a)

array([[33]])

In [58]:

b=matris_carpimi(G,H)

In [59]:
b.dot(I)

array([[33]])

In [60]:
matris_carpimi(b,I)

array([[33]])