In [1]:
import pandas as pd
import numpy as np

In [2]:
a=np.array([[1,1,2],[2,1,3]])

In [3]:
a

array([[1, 1, 2],
       [2, 1, 3]])

In [4]:
b=np.array([[1,1],[2,3],[1,2]])

In [5]:
b

array([[1, 1],
       [2, 3],
       [1, 2]])

In [6]:
c=a.dot(b)

In [7]:
c

array([[ 5,  8],
       [ 7, 11]])

In [8]:
def vektörel_çarpım(a,b):
    return a.dot(b)
  



In [9]:
vektörel_çarpım(a,b)

array([[ 5,  8],
       [ 7, 11]])

In [10]:
vektörel_çarpım(b,a)

array([[ 3,  2,  5],
       [ 8,  5, 13],
       [ 5,  3,  8]])

In [14]:
a=np.array([[1,2],[3,4]])

In [15]:
b=np.array([[1,1],[0,1],[1,2]])

In [16]:
a.dot(b)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [22]:
crude_oil_1=np.array([3/4,2/3,1/4])

In [23]:
c1=

SyntaxError: invalid syntax (<ipython-input-23-75ce0756d316>, line 1)

In [19]:
crude_oil_2=np.array([1/4,1/3,3/4])

In [ ]:
c2=

In [21]:
c1_c2=np.array([[3/4,2/3,1/4],[1/4,1/3,3/4]])

In [20]:
pU_rU_rL=np.array([10,6,5])

In [24]:
c1_c2.dot(pU_rU_rL)

array([12.75,  8.25])

In [26]:
A=np.array([[1,1,2],[2,1,3]]) ; B=np.array([[1,1],[2,3],[1,2]])

In [27]:
A[1]

array([2, 1, 3])

In [28]:
vektörel_çarpım(A,B)

array([[ 5,  8],
       [ 7, 11]])

In [30]:
vektörel_çarpım(A,B)[0]

array([5, 8])

In [31]:
vektörel_çarpım(A[0],B)

array([5, 8])

In [32]:
A=np.array([[1,1,2],[2,1,3]]) ; B=np.array([[1,1],[2,3],[1,2]])

In [43]:
B[:,1]

array([1, 3, 2])

In [46]:
vektörel_çarpım(A,B)[:,1]

array([ 8, 11])

In [47]:
vektörel_çarpım(A,B[:,1])

array([ 8, 11])

#sütun çağırma

In [49]:
A=np.array([1,2]);B=np.array([[2,3],[4,5]]);C=np.array([2,1])

In [61]:
AB=np.array(vektörel_çarpım(A,B))

In [62]:
AB

array([10, 13])

In [63]:
vektörel_çarpım(AB,C)

33

In [64]:
BC=np.array(vektörel_çarpım(B,C))

In [65]:
BC

array([ 7, 13])

In [68]:
vektörel_çarpım(A,BC)

33

In [ ]:
# 