<h1>Temel Lineer Cebir</h1>

<u><strong>01.02.2020</strong></u>

In [3]:
import pandas as pd
import numpy as np

In [6]:
A = np.array([[1,1,2],[2,1,3]])
B = np.array([[1,1],[2,3],[1,2]])

In [12]:
print("C = AB\n=",np.dot(A,B))

C = AB
= [[ 5  8]
 [ 7 11]]


In [45]:
def VektorelCarpim(A,B):
    try:
        return np.dot(A,B)
    except:
        print("Vektorel Carpim Yapilamiyor!..(Boyut Uyuşmazlığı)")

In [46]:
print("Vektorel Carpim Sonucu (AB) = \n",VektorelCarpim(np.array([[3],[4]]),np.array([[1,2]])))

Vektorel Carpim Sonucu (AB) = 
 [[3 6]
 [4 8]]


In [47]:
print("Vektorel Carpim Sonucu (BA) = \n",VektorelCarpim(np.array([1,2]),np.array([[3],[4]])))

Vektorel Carpim Sonucu (BA) = 
 [11]


In [48]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,1],[0,1],[1,2]])
VektorelCarpim(A,B)


Vektorel Carpim Yapilamiyor!..(Boyut Uyuşmazlığı)


<h3>Örnek 1.1</h3>

In [54]:
c1 = np.array([3/4,2/3,1/4]) #Ham Petrol 1
c2 = np.array([1/4,1/3,3/4]) #Ham Petrol 2
c = np.array([c1,c2]) #Gerekli Ham Petroller

In [57]:
pu = 10
ru = 6
rl =5
arr = np.array([[pu],[ru],[rl]])
arr



array([[10],
       [ 6],
       [ 5]])

In [59]:
print("Gallons Required = \n",VektorelCarpim(c,arr))

Gallons Required = 
 [[12.75]
 [ 8.25]]


In [62]:
df = pd.DataFrame({
    "Crude 1" : c1,
    "Crude 2" : c2,
})
df

Crude 1   Crude 2
0  0.750000  0.250000
1  0.666667  0.333333
2  0.250000  0.750000

<h2>Matris Çarpımının Özellikleri</h2>

<strong><u>Kural 1 :</u></strong> 1.Matrisin 1.Satırı x 2.Matris = (1.Matris x 2.Matris) sonucunun 1. Satırı

In [68]:
A = np.array([[1,1,2],[2,1,3]])
B = np.array([[1,1],[2,3],[1,2]])


In [71]:
arg1 = VektorelCarpim(A[0],B)

In [72]:
arg2 = (VektorelCarpim(A,B))[0]

In [73]:
arg1 == arg2

array([ True,  True])

<strong><u>Kural 2 :</u></strong> 1.Matris x 2.Matrisin 1.Sütunu = (1.Matris x 2.Matris) sonucunun 1. Sütununu verir

In [88]:
arg3 = VektorelCarpim(A,B[:,0])
arg4 = (VektorelCarpim(A,B))[:,0]

In [90]:
arg3 == arg4

array([ True,  True])

<strong><u>3. Kural :</u></strong> A(BC) = (AB)C

In [93]:
A = [1,2]
B = [[2,3],[4,5]]
C = [[2],[1]]

In [94]:
arg5 = VektorelCarpim(A,VektorelCarpim(B,C))
arg6 = VektorelCarpim(VektorelCarpim(A,B),C)

In [96]:
arg5 == arg6

array([ True])