In [1]:
import pandas as pd
import numpy as np

In [92]:
v1=[1,3]

In [93]:
v2=[2,4]

In [94]:
matrix=[v1,v2]

In [95]:
matrix

[[1, 3], [2, 4]]

In [96]:
np.array(matrix).shape

(2, 2)

In [97]:
pd.DataFrame(np.array(matrix) )

0  1
0  1  3
1  2  4

#  Matris ve Vektör


In [98]:
1 #Scalar

1

In [99]:
[1] # Vektör

[1]

In [100]:
[1,1] # Vektör 1,2

[1, 1]

In [101]:
[[1,1],[1,1]] # Matris 2,2

[[1, 1], [1, 1]]

In [102]:
a00=1;a01=0;a10=7;a11=3;a20=7;a21=3

In [103]:
A=np.array([[a00,a01],[a10,a11],[a20,a21]])

In [104]:
pd.DataFrame(A)

0  1
0  1  0
1  7  3
2  7  3

In [105]:
A.shape[1]

2

In [106]:
A[1][1]

3

In [107]:
A=np.array([1,2])

In [108]:
A

array([1, 2])

In [109]:
A.shape

(2,)

In [110]:
Satır_Vektor=np.array([1,2,3,34,2])

In [111]:
u=np.array([1,2]);v=np.array([1,-3])
w=np.array([-1,-2])

In [112]:
u =np.array( [1, 2, 3] )

In [113]:
v=  np.array( [2,1,2] )

In [114]:
u.dot(v)

10

In [115]:
u.view

<function ndarray.view>

In [116]:
u+v #matris toplama

array([3, 3, 5])

In [117]:
u=np.array([1,2]);v=np.array([2,1])
w=u+v;w

array([3, 3])

In [118]:
def doğru_parçası(c,u,v):
       return c*u + (1 - c)*v

In [119]:
c=0
doğru_parçası(c,u,v)

array([2, 1])

In [120]:
c=1
doğru_parçası(c,u,v)

array([1, 2])

In [121]:
c=0.5
doğru_parçası(c,u,v)

array([1.5, 1.5])

In [122]:
# Tranpozu, Devrik

In [123]:
A=np.array([[a00,a01],[a10,a11],[a20,a21]])

In [124]:
A

array([[1, 0],
       [7, 3],
       [7, 3]])

In [125]:
A.T

array([[1, 7, 7],
       [0, 3, 3]])

In [126]:
A.transpose().shape

(2, 3)

In [127]:
A.shape

(3, 2)

In [128]:
A.T.T

array([[1, 0],
       [7, 3],
       [7, 3]])

In [129]:
A=np.array([[1,1,2],[2,1,3]])
B=np.array([[1,1],[2,3],[1,2]])
A.dot(B)

array([[ 5,  8],
       [ 7, 11]])

In [130]:
def vektörel_çarpım(A,B):
    return A.dot(B)

In [131]:
A=np.array([[3],[4]]);B=np.array([[1, 2]]);

In [132]:
vektörel_çarpım(A,B)

array([[3, 6],
       [4, 8]])

In [133]:
vektörel_çarpım(B,A)

 # LEBG

array([[11]])

![image.png](attachment:image.png)

In [134]:
A=np.array([[1,2],[3,4]]);B=np.array([[1,1],[0,1],[1,2]]);

In [135]:
vektörel_çarpım(A,B) # Vektörel çarpımda ilk matrisin sütün sayısı ile ikinci matrisin satır sayısı aynı olmalı

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
vektörel_çarpım(B,A)

In [ ]:
PremiumUnleaded=np.array([3/4,1/4])
RegularUnleaded=np.array([2/3,1/3])
RegularLeaded=np.array([1/4,3/4])

In [ ]:
mainTable=np.array([PremiumUnleaded,RegularUnleaded,RegularLeaded])

In [ ]:
mainDataFrame=pd.DataFrame(mainTable,columns=("crude1","crude2"))

In [ ]:
mainDataFrame.index=["PremiumUnleaded","RegularUnleaded","RegularLeaded"]

In [ ]:
mainDataFrame

In [ ]:
Stock=np.array([10,6,5])

In [ ]:
vektörel_çarpım(Stock,mainDataFrame)

In [ ]:
# Kural 1 Satır

In [ ]:
A=np.array([[1,1,2],[2,1,3]]);B=np.array([[1,1],[2,3],[1,2]])

In [ ]:
A[1]

In [ ]:
vektörel_çarpım(A,B)

In [ ]:
vektörel_çarpım(A,B)[0]

In [ ]:
vektörel_çarpım(A[0],B)

In [ ]:
# Kural 2 Sütün

In [ ]:
vektörel_çarpım(A,B[:,0])

In [ ]:
vektörel_çarpım(A,B)[:,0]

In [ ]:
# Geçişkenlik Kuralı

In [ ]:
A=np.array([1,2]) ; B=np.array([[2,3],[4,5]]);C=np.array([[2],[1]])

In [ ]:
A

In [ ]:
B

In [ ]:
C

In [ ]:
vektörel_çarpım(vektörel_çarpım(A,B),C)

In [ ]:
vektörel_çarpım(A,vektörel_çarpım(B,C))

In [ ]:
vektörel_çarpım(vektörel_çarpım(A,B),C)==vektörel_çarpım(A,vektörel_çarpım(B,C))

## Problemler



### 1. Problem

In [ ]:

A=np.array([[1,2,3],[4,5,6],[7,8,9]]);B=np.array([[1,2],[0,-1],[1,2]])

In [ ]:

print("A :\n", A,"\n")


In [ ]:
print("B :\n", B,"\n")

In [ ]:
 
print("-A :\n", A*-1,"\n")


In [ ]:
print("3A :\n", A*3,"\n")

In [ ]:

print("A+2B : \n",A+2*B)

In [ ]:

print("A transpose : \n" , A.T  )

In [ ]:
      
print("B transpose : \n" , B.T  )

In [ ]:
print("AB transpose : \n" , A.dot(B)  )

In [ ]:
print("BA transpose : \n" , B.dot(A)  )

### 2. Problem

In [ ]:
Bira1=[.5,.3,.2]
Bira2=[0,.7,.3]
Bira3=[.1,.3,.6]
Bira_dict={"Bira1":Bira1
          ,"Bira2":Bira2,
          "Bira3":Bira3}

In [ ]:
Bira_df=pd.DataFrame(Bira_dict,index=["Bira1","Bira2","Bira3"])

In [ ]:
Bira_df

In [ ]:
x1=pd.DataFrame({"t1":[0,10,90]},index=["Bira1","Bira2","Bira3"])

In [ ]:
x1

In [ ]:
Bira_df.shape

In [ ]:
x1.shape

In [ ]:
y1=Bira_df.dot(x1)

In [ ]:
y1

### 3.Problem

In [ ]:
A=np.array([1,2]) ; B=np.array([[2,3],[4,5]]);C=np.array([[2],[1]])
vektörel_çarpım(vektörel_çarpım(A,B),C)==vektörel_çarpım(A,vektörel_çarpım(B,C))

### 4.Problem

In [ ]:
A=np.array([1,2]) ; B=np.array([[2,3],[4,5]])
print(" (AB)T :\n", vektörel_çarpım(A,B).T)
print(" BT*AT :\n",vektörel_çarpım(B.T,A.T))
vektörel_çarpım(A,B).T==vektörel_çarpım(B.T,A.T)

### 5.Problem

In [ ]:
A=np.array([[1,2],[2,1]]);
print(" A : \n",A)
print(" A.T : \n",A.T)

print(" A==A.T : \n",A==A.T  )

In [ ]:
# a 
print("A*A.T simetrik \n" , A.dot(A.T)==A.dot(A.T).T)

In [ ]:
# b 
print("A+A.T simetrik \n" , (A+A.T)==(A+A.T).T)

### 6.Problem

In [ ]:
A=np.array([[1,1],[1,1]]);
B=np.array([[2,1],[1,2]]);

In [ ]:
A.shape

In [ ]:
B.shape

In [ ]:
n=A.shape[0]

In [ ]:
n**3 # Gereken çarpma sayısı

In [ ]:
n**3-n**2 # Gereken toplama sayısı

### 7.Problem

In [ ]:
def matriks_izi(A):
    return np.array([A[i][i] for i in range(len(A))])

In [ ]:
# a
matriks_izi(A+B)==(matriks_izi(A)+matriks_izi(B))

In [ ]:
# b
matriks_izi(vektörel_çarpım(A,B))  == matriks_izi(vektörel_çarpım(B,A))

## Lineer Denklemlerin Matrisleri

In [ ]:
a11=None;a12=None;a13=None;a21=None;a22=None;a23=None; a31=None;a32=None;a33=None;

A=np.array([[a11,a12,a13],
[a21,a22,a23],
[a31,a32,a33]])

In [ ]:
A

In [ ]:
x11=None;x12=None;x13=None;x21=None;x22=None;x23=None; x31=None;x32=None;x33=None;

X=np.array([[x11,x12,x13],
[x21,x22,x23],
[x31,x32,x33]])

In [ ]:
b1=None;b2=None;b3=None;
B=np.array([b1,b2,b3])

In [ ]:
B

In [ ]:
A.dot(X)==B

<b><i> X değişken , A ve B sabittir. A*X=B </b></i> 

<b> Örnek Olarak : </b>  

In [2]:
A=np.array([[1,2],[2,-1]])
B=np.array([[5],[0]])

In [3]:
A

array([[ 1,  2],
       [ 2, -1]])

In [4]:
B

array([[5],
       [0]])

In [5]:
X=np.array([[1],[2]])

In [6]:
A.dot(X)==B

array([[ True],
       [ True]])

In [7]:
A

array([[ 1,  2],
       [ 2, -1]])

In [ ]:
B

In [8]:
# A|b
np.concatenate((A,B), axis=1)

array([[ 1,  2,  5],
       [ 2, -1,  0]])

In [9]:
# Problem 

A=np.array([[1,-1],[2,1],[1,3]])
B=np.array([[4],[6],[8]])

np.concatenate((A,B), axis=1)

array([[ 1, -1,  4],
       [ 2,  1,  6],
       [ 1,  3,  8]])

## Gauss-Jordan Metodu ile Lineer Denklem Çözümü

In [ ]:
# Durum 1 : Sistemin çözümü yoktur.
# Durum 2 : Sistemin tek bir çözümü vardır.
# Durum 3 : Sistemin sonsuz çözümü vardır.

#### Satır Operasyonları (ERO)

In [137]:
# ERO 1  : herhangi bir satırı bir sabit ile çarpmak 
A=np.array([[11,-1],[12,1],[1,37]])

In [138]:
A

array([[11, -1],
       [12,  1],
       [ 1, 37]])

In [139]:
A[0]=A[0]*33

In [140]:
A

array([[363, -33],
       [ 12,   1],
       [  1,  37]])

In [151]:
# ERO 2  : herhangi  diğer satıra eklemek
A=np.array([[11,-1],[12,1],[1,37]])
A[2]=A[2]+A[0]*5
A

array([[11, -1],
       [12,  1],
       [56, 32]])

In [153]:
# ERO 3 : İki satırın yerlerini değiştirmek 
A=np.array([[11,-1],[12,1],[1,37]])
Geçici_Değişken=A[0].copy() # .copy() yapmazsak aynı yere kaydediyor.
A[0]=A[2]
A[2]=Geçici_Değişken
A


array([[ 1, 37],
       [12,  1],
       [11, -1]])

In [10]:
A=np.array([[11,-1],[12,1],[1,37]])
Geçici_Değişken=A[0] # .copy() yapmazsak aynı yere kaydediyor.
A[0]=A[2]
A[2]=Geçici_Değişken
A

array([[ 1, 37],
       [12,  1],
       [ 1, 37]])

In [175]:
# x1+x2 = 2  ve 2x1 + 4x2 =7 denklemini bu öğrendiklerimiz ile çözelim.

A=np.array([[1,1,2],[2,4,7.0]],float)
A



array([[1., 1., 2.],
       [2., 4., 7.]])

In [176]:
A[1]=A[1]/2  # ERO1
A

array([[1. , 1. , 2. ],
       [1. , 2. , 3.5]])

In [177]:
A[1]=A[1]-A[0]  # ERO2
A


array([[1. , 1. , 2. ],
       [0. , 1. , 1.5]])

In [178]:
A[0]=A[0]-A[1]  # ERO2
A

array([[1. , 0. , 0.5],
       [0. , 1. , 1.5]])

In [182]:
[x1,x2]=A[:,2]
print("x1 : {x1} ve x2: {x2}".format(x1=x1,x2=x2))




x1 : 0.5 ve x2: 1.5


### Gauss Jordan İle Çözüm 

In [11]:
A=np.array([[2,2,1],[2,-1,2],[1,-1,2]],float) # Katsayı
b=np.array([[9],[6],[5]],float) # y 

Ab=np.concatenate((A,b),axis=1) # matrisleri birleştirdik

Ab 


array([[ 2.,  2.,  1.,  9.],
       [ 2., -1.,  2.,  6.],
       [ 1., -1.,  2.,  5.]])

In [12]:
Ab1=Ab.copy() # ilk işlem olarak birinci satırın ilk elemanı 1 olacak şekilde ERO işlemi yaptık
Ab1[0]=Ab1[0]/2
Ab1

array([[ 1. ,  1. ,  0.5,  4.5],
       [ 2. , -1. ,  2. ,  6. ],
       [ 1. , -1. ,  2. ,  5. ]])

In [16]:
Ab2=Ab1.copy() # Sonrasında 2 ve 3. satırların ilk sütünlarını 0 olacak şekilde ERO işlemleri yapıyoruz.
Ab2[1]=Ab2[1]-Ab1[1][0]*Ab1[0]
Ab2

array([[ 1. ,  1. ,  0.5,  4.5],
       [ 0. , -3. ,  1. , -3. ],
       [ 1. , -1. ,  2. ,  5. ]])

In [17]:
Ab3=Ab2.copy()
Ab3[2]=Ab2[2]-Ab2[2][0]*Ab2[0]

Ab3

array([[ 1. ,  1. ,  0.5,  4.5],
       [ 0. , -3. ,  1. , -3. ],
       [ 0. , -2. ,  1.5,  0.5]])

In [18]:
Ab3[1]=Ab3[1]*(-1/3) # Yukarıda birinci satır için yaptığımız işlemleri 2. ve 3 satırlar için de yapıyoruz.

Ab3[0]=Ab3[0]-Ab3[1]

Ab3[2]=Ab3[2]+2*Ab3[1]
Ab3

array([[ 1.        ,  0.        ,  0.83333333,  3.5       ],
       [-0.        ,  1.        , -0.33333333,  1.        ],
       [ 0.        ,  0.        ,  0.83333333,  2.5       ]])

In [19]:
Ab4=Ab3.copy()

Ab4[2]=Ab4[2]*(6/5)

Ab4[0]=Ab4[0]-Ab4[2]*(5/6)

Ab4[1]=Ab4[1]+Ab4[2]*(1/3)

In [20]:
np.round(Ab4,6) 

array([[ 1.,  0., -0.,  1.],
       [ 0.,  1.,  0.,  2.],
       [ 0.,  0.,  1.,  3.]])

In [21]:
[x1,x2,x3]=Ab4[:,3]

In [22]:
print("x1 : {x1} , x2: {x2} ve x3: {x3} olarak bulunmuştur.".format(x1=x1,x2=x2,x3=x3))

x1 : 1.0 , x2: 2.0 ve x3: 3.0 olarak bulunmuştur.


In [16]:
## Çözümsüz veya Sonsuz Çözümlü Denklemler

In [23]:
# Örnek 6
A=np.array([[1,2],[2,4]]);b=np.array([[3],[4]])
Ab=np.concatenate((A,b),axis=1)

In [24]:
Ab

array([[1, 2, 3],
       [2, 4, 4]])

In [25]:
Ab[1]=Ab[1]-2*Ab[0]

In [26]:
Ab

array([[ 1,  2,  3],
       [ 0,  0, -2]])

In [22]:
Ab[1] # x1 ve x2 ye ne verirsek verelim sonuç -2 olmaz. Bu yüzden ÇÖZÜMSÜZDÜR.

array([ 0,  0, -2])

In [23]:
# Eğer A nın bir satırı tamamen 0 oluyor ve buna karşılık b nin o satıra ait değeri 0 olmuyorsa bu sistemin çözümü yoktur.

In [24]:
# Örnek 7

In [34]:
A=np.array([[1,1,0],[0,1,1],[1,2,1]]);b=np.array([[1],[3],[4]]);
Ab=np.concatenate((A,b),axis=1)

In [5]:
Ab[2]=Ab[2]-Ab[0]

In [6]:
Ab

array([[1, 1, 0, 1],
       [0, 1, 1, 3],
       [0, 1, 1, 3]])

In [7]:
Ab[0]=Ab[0]-Ab[1]

In [8]:
Ab[2]=Ab[2]-Ab[1]

In [9]:
Ab

array([[ 1,  0, -1, -2],
       [ 0,  1,  1,  3],
       [ 0,  0,  0,  0]])

In [114]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [110]:
# Gauss Jordan Metodu 

def GaussJordan(A,b):
    """ 
    Gauss Jordan methodu ile satır işlemleri yapıp, değişkenleri 
    hesaplar.Öncelikle katsayı matrisi ile sonuç matrisi birleştirilir.
    İlk olarak köşegen elemanın 0'a eşitliği kontrol edilir.
    Daha sonrasında ona ait sütündaki diğer elemanlar 0 olacak 
    şekilde satır işlemleri yapılır. Bütün satırların üzerinden 
    bu yöntemle geçilir. 
    
    """
    
    # Adım 1 : A|b matrisini oluştur. 
    
    Ab=np.concatenate((A,b),axis=1)
    satır_sayısı=Ab.shape[0]
    sutun_sayısı=Ab.shape[1]
    
    for i in range(satır_sayısı):         
        if Ab[i][i]==0:
            Geçici=Ab[i].copy()
            satır_indisleri=[a for a in range(i,satır_sayısı) if Ab[a][i]!=0]
            if satır_indisleri:
                Ab[i]=Ab[satır_indisleri[0]].copy()
                Ab[satır_indisleri[0]]=Geçici
            else:
                print(str(i)+". satırından sonra işlem yapılamamaktadır")
                return Ab
        Ab[i]=Ab[i]/Ab[i][i]    
        for s in range(satır_sayısı): 
            if i==s:
                pass
            else:
                Ab[s]=Ab[s]-Ab[i]*Ab[s][i]

    return Ab

In [113]:
## Durum 1 

A=np.array([[1,0,0,1],[0,1,0,2],[0,0,1,3],[0,0,0,0],[0,0,0,0]],float)
b=np.array([[1],[1],[-1],[0],[2]],float)

GaussJordan(A,b)

3. satırından sonra işlem yapılamamaktadır


array([[ 1.,  0.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  2.,  1.],
       [ 0.,  0.,  1.,  3., -1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.]])

In [123]:
# Durum 2

A=np.array([[2,2, 1],[2,-1,2],[1,-1,2]],float)
b=np.array([[9],[6],[5]],float)
print(np.concatenate((A,b),axis=1))
GaussJordan(A,b)

[[ 2.  2.  1.  9.]
 [ 2. -1.  2.  6.]
 [ 1. -1.  2.  5.]]


array([[1., 0., 0., 1.],
       [0., 1., 0., 2.],
       [0., 0., 1., 3.]])

In [124]:
# Durum 3 
A=np.array([[1,0,0,1,1],[0,1,0,2,0],[0,0,1,0,1],[0,0,0,0,0]],float)
b=np.array([[3],[2],[1],[0]],float)
print(np.concatenate((A,b),axis=1))
GaussJordan(A,b)

[[1. 0. 0. 1. 1. 3.]
 [0. 1. 0. 2. 0. 2.]
 [0. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0.]]
3. satırından sonra işlem yapılamamaktadır


array([[1., 0., 0., 1., 1., 3.],
       [0., 1., 0., 2., 0., 2.],
       [0., 0., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [55]:
A=np.array([[0,1,1],[0,2,5],[0,35,1]],float)
b=np.array([[3],[4],[5]],float)

In [56]:
a=DoğrusalDenklem(A,b)

3 bilinmeyenli doğrusal denklem sistemi oluşturulmuştur.


In [57]:
a.GaussJordan()

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 1., 3.]])

In [193]:
class DoğrusalDenklem():
    
    def __init__(self,A,b):
        self.denklem=np.concatenate((A,b),axis=1)
        self.satır_sayısı=self.denklem.shape[0]
        self.sütün_sayısı=self.denklem.shape[1]
        print("{n} bilinmeyenli doğrusal denklem sistemi oluşturulmuştur.".format(n=A.shape[1],Ab=self.denklem))
    
    def __str__(self):
        return "Denklem sistemi ----> \n {Ab}".format(Ab=self.denklem)
    
    def __len__(self):
        return self.denklem.shape[0]

    def __del__(self):
        return  "Doğrusal denklem silinmiştir." 
    
    def GaussJordan(self):
        """ 
        Gauss Jordan methodu ile satır işlemleri yapıp, değişkenleri 
        hesaplar.Öncelikle katsayı matrisi ile sonuç matrisi birleştirilir.
        İlk olarak köşegen elemanın 0'a eşitliği kontrol edilir.
        Daha sonrasında ona ait sütündaki diğer elemanlar 0 olacak 
        şekilde satır işlemleri yapılır. Bütün satırların üzerinden 
        bu yöntemle geçilir. 

        """

        # Adım 1 : A|b matrisini oluştur. 

        Ab=self.denklem.copy()
        satır_sayısı=Ab.shape[0]
        sutun_sayısı=Ab.shape[1]

        for i in range(satır_sayısı):         
            if Ab[i][i]==0:
                Geçici=Ab[i].copy()
                satır_indisleri=[a for a in range(i,satır_sayısı) if Ab[a][i]!=0]
                if satır_indisleri:
                    Ab[i]=Ab[satır_indisleri[0]].copy()
                    Ab[satır_indisleri[0]]=Geçici
                else:
                    print(str(i)+". satırından sonra işlem yapılamamaktadır")
                    return Ab
            Ab[i]=Ab[i]/Ab[i][i]    
            for s in range(satır_sayısı): 
                if i==s:
                    pass
                else:
                    Ab[s]=Ab[s]-Ab[i]*Ab[s][i]

        return Ab

    def çözüm_durumu(self):
        çözüm=self.GaussJordan()
        satır_sayısı=self.satır_sayısı
        sutun_sayısı= self.sütün_sayısı
        tekÇözüm=False
        
        for i in range(satır_sayısı):      
            if all(çözüm[i,:sutun_sayısı-1]==0) and çözüm[i,sutun_sayısı-1]!=0:
                print("Denklem Kümesi Çözümsüzdür.")
                return "çözümsüz"  
        
        if satır_sayısı==(sutun_sayısı-1):
            i=0
            while i<satır_sayısı and çözüm[i][i]==1:
                i+=1

            if i==satır_sayısı:
                tekÇözüm=True
                print("Denklem Kümesinin Tek Çözümü mevcuttur.")
                return "tek"
        else:
            print("Denklem Kümesinin Sonsuz Çözümü mevcuttur.")
            return "sonsuz"

array([ True, False,  True])

False

### Ana Değişkenler ve Doğrusal Denklemlerde Çözümleri 

<i> Doğrusal denklem sistemlerini çözdükten sonra eğer bir satırda sadece bir sütünda 1 katsayısı var ve diğer sütünların katsayıları 0 ise bu değişkene <b> esas değişken (BV) </b>  denir.   </i>  <i> Aksi durumdaki değişkenler <b>  esas olmayan  (NBV)</b>  değişkenlerdir  .   </i>

In [151]:
## Durum 1 

A=np.array([[1,0,0,1],[0,1,0,2],[0,0,1,3],[0,0,0,0],[0,0,0,0]],float)
b=np.array([[1],[1],[-1],[0],[2]],float)

In [152]:
örnek_denklem_1=DoğrusalDenklem(A,b)

4 bilinmeyenli doğrusal denklem sistemi oluşturulmuştur.


In [153]:
örnek_denklem_1.denklem

array([[ 1.,  0.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  2.,  1.],
       [ 0.,  0.,  1.,  3., -1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.]])

In [154]:
örnek_denklem_1.GaussJordan()

3. satırından sonra işlem yapılamamaktadır


array([[ 1.,  0.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  2.,  1.],
       [ 0.,  0.,  1.,  3., -1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.]])

In [155]:
sonuç=örnek_denklem_1.çözüm_durumu()

3. satırından sonra işlem yapılamamaktadır
Denklem Kümesi Çözümsüzdür.


In [156]:
print(sonuç)

çözümsüz


In [157]:
# Güncellenmiş Gauss Jordan
GaussJordan(A,b)

3. satırından sonra işlem yapılamamaktadır


array([[ 1.,  0.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  2.,  1.],
       [ 0.,  0.,  1.,  3., -1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.]])

In [158]:
# Durum 2

A=np.array([[2,2, 1],[2,-1,2],[1,-1,2]],float)
b=np.array([[9],[6],[5]],float)


In [159]:
örnek_denklem_2=DoğrusalDenklem(A,b)

3 bilinmeyenli doğrusal denklem sistemi oluşturulmuştur.


In [160]:
örnek_denklem_2.GaussJordan()

array([[1., 0., 0., 1.],
       [0., 1., 0., 2.],
       [0., 0., 1., 3.]])

In [161]:
sonuç=örnek_denklem_2.çözüm_durumu();

Denklem Kümesinin Tek Çözümü mevcuttur.


In [162]:
print(sonuç)

tek


In [163]:
# Durum 3 
A=np.array([[1,0,0,1,1],[0,1,0,2,0],[0,0,1,0,1],[0,0,0,0,0]],float)
b=np.array([[3],[2],[1],[0]],float)

In [164]:
örnek_denklem_3=DoğrusalDenklem(A,b)

5 bilinmeyenli doğrusal denklem sistemi oluşturulmuştur.


In [165]:
örnek_denklem_3.denklem

array([[1., 0., 0., 1., 1., 3.],
       [0., 1., 0., 2., 0., 2.],
       [0., 0., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [166]:
örnek_denklem_3.GaussJordan()

3. satırından sonra işlem yapılamamaktadır


array([[1., 0., 0., 1., 1., 3.],
       [0., 1., 0., 2., 0., 2.],
       [0., 0., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [167]:
sonuç=örnek_denklem_3.çözüm_durumu()

3. satırından sonra işlem yapılamamaktadır
Denklem Kümesinin Sonsuz Çözümü mevcuttur.


In [168]:
sonuç

'sonsuz'

### Problemler 




#### 1-8  Problemler

In [194]:
def problem_çözer(A,b):
    denklem=DoğrusalDenklem(A,b)
    print("Çözüm: \n",denklem.GaussJordan(),"\n")
    print("Çözüm durumu : ",denklem.çözüm_durumu(),"\n")

In [195]:
# 1 
A=np.array([[1,1,0,1],[0,1,1,0],[1,2,1,1]],float)
b=np.array([[3],[4],[8]],float)
problem_çözer(A,b)

4 bilinmeyenli doğrusal denklem sistemi oluşturulmuştur.
2. satırından sonra işlem yapılamamaktadır
Çözüm: 
 [[ 1.  0. -1.  1. -1.]
 [ 0.  1.  1.  0.  4.]
 [ 0.  0.  0.  0.  1.]] 

2. satırından sonra işlem yapılamamaktadır
Denklem Kümesi Çözümsüzdür.
Çözüm durumu :  çözümsüz 



In [196]:
# 2 
A=np.array([[1,1,1],[1,2,0]],float)
b=np.array([[4],[6]],float)
problem_çözer(A,b)

3 bilinmeyenli doğrusal denklem sistemi oluşturulmuştur.
Çözüm: 
 [[ 1.  0.  2.  2.]
 [ 0.  1. -1.  2.]] 

Denklem Kümesinin Sonsuz Çözümü mevcuttur.
Çözüm durumu :  sonsuz 



In [197]:
# 3 
A=np.array([[1,1],[2,1],[3,2]],float)
b=np.array([[1],[3],[4]],float)
problem_çözer(A,b)

2 bilinmeyenli doğrusal denklem sistemi oluşturulmuştur.
2. satırından sonra işlem yapılamamaktadır
Çözüm: 
 [[ 1.  0.  2.]
 [-0.  1. -1.]
 [ 0.  0.  0.]] 

2. satırından sonra işlem yapılamamaktadır
Denklem Kümesinin Sonsuz Çözümü mevcuttur.
Çözüm durumu :  sonsuz 



In [198]:
# 4 
A=np.array([[2,-1,1,1],[1,1,1,0]],float)
b=np.array([[6],[4]],float)
problem_çözer(A,b)

4 bilinmeyenli doğrusal denklem sistemi oluşturulmuştur.
Çözüm: 
 [[ 1.          0.          0.66666667  0.33333333  3.33333333]
 [ 0.          1.          0.33333333 -0.33333333  0.66666667]] 

Denklem Kümesinin Sonsuz Çözümü mevcuttur.
Çözüm durumu :  sonsuz 



In [199]:
# 5 
A=np.array([[1,0,0,1],[0,1,0,2],[0,0,1,.5],[0,0,2,1]],float)
b=np.array([[5],[5],[1],[3]],float)
problem_çözer(A,b)

4 bilinmeyenli doğrusal denklem sistemi oluşturulmuştur.
3. satırından sonra işlem yapılamamaktadır
Çözüm: 
 [[1.  0.  0.  1.  5. ]
 [0.  1.  0.  2.  5. ]
 [0.  0.  1.  0.5 1. ]
 [0.  0.  0.  0.  1. ]] 

3. satırından sonra işlem yapılamamaktadır
Denklem Kümesi Çözümsüzdür.
Çözüm durumu :  çözümsüz 



In [200]:
# 6
A=np.array([[0,2,2 ],[1,2,1 ],[0,1,-1 ]],float)
b=np.array([[4],[4],[0]],float)
problem_çözer(A,b)

3 bilinmeyenli doğrusal denklem sistemi oluşturulmuştur.
Çözüm: 
 [[ 1.  0.  0.  1.]
 [ 0.  1.  0.  1.]
 [-0. -0.  1.  1.]] 

Denklem Kümesinin Tek Çözümü mevcuttur.
Çözüm durumu :  tek 



In [201]:
# 7
A=np.array([[1,1,0 ],[0,-1,2 ],[0,1,1 ]],float)
b=np.array([[2],[3],[3]],float)
problem_çözer(A,b)

3 bilinmeyenli doğrusal denklem sistemi oluşturulmuştur.
Çözüm: 
 [[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 2.]] 

Denklem Kümesinin Tek Çözümü mevcuttur.
Çözüm durumu :  tek 



In [203]:
# 8
A=np.array([[1,1,1 ,0],[0,1,2,1 ],[0,0,0,1 ]],float)
b=np.array([[1],[2],[3]],float)
problem_çözer(A,b)

4 bilinmeyenli doğrusal denklem sistemi oluşturulmuştur.
2. satırından sonra işlem yapılamamaktadır
Çözüm: 
 [[ 1.  0. -1. -1. -1.]
 [ 0.  1.  2.  1.  2.]
 [ 0.  0.  0.  1.  3.]] 

2. satırından sonra işlem yapılamamaktadır
Denklem Kümesinin Sonsuz Çözümü mevcuttur.
Çözüm durumu :  sonsuz 



In [209]:
# 9 

A=np.array([[1,1,1 ,0],[0,1,2,1 ],[0,0,0,1 ]],float)
b=np.array([[1],[2],[3]],float)
problem_çözer(A,b)
değişken_sayısı=A.shape[1]

4 bilinmeyenli doğrusal denklem sistemi oluşturulmuştur.
2. satırından sonra işlem yapılamamaktadır
Çözüm: 
 [[ 1.  0. -1. -1. -1.]
 [ 0.  1.  2.  1.  2.]
 [ 0.  0.  0.  1.  3.]] 

2. satırından sonra işlem yapılamamaktadır
Denklem Kümesinin Sonsuz Çözümü mevcuttur.
Çözüm durumu :  sonsuz 



In [205]:
bulunabilecek_değişken_sayısı=b.shape[0]

In [206]:
bulunabilecek_değişken_sayısı

3

In [207]:
değişken_sayısı

4

In [208]:
if bulunabilecek_değişken_sayısı>değişken_sayısı:
    print("Tek bir çözüm olma şansı mevcuttur.")
else:
    print("Tek bir çözüm olma şansı mevcut değildir.")

Tek bir çözüm olma şansı mevcut değildir.


In [2]:
"Deneme"

'Deneme'