In [2]:
import pandas as pd
import numpy as np

In [3]:
v1=[1,3]

In [4]:
v2=[2,4]

In [5]:
matrix=[v1,v2]

In [6]:
matrix

[[1, 3], [2, 4]]

In [7]:
np.array(matrix).shape

(2, 2)

In [8]:
pd.DataFrame(np.array(matrix) )

0  1
0  1  3
1  2  4

#  Matris ve Vektör


In [9]:
1 #Scalar

1

In [10]:
[1] # Vektör

[1]

In [11]:
[1,1] # Vektör 1,2

[1, 1]

In [12]:
[[1,1],[1,1]] # Matris 2,2

[[1, 1], [1, 1]]

In [13]:
a00=1;a01=0;a10=7;a11=3;a20=7;a21=3

In [14]:
A=np.array([[a00,a01],[a10,a11],[a20,a21]])

In [15]:
pd.DataFrame(A)

0  1
0  1  0
1  7  3
2  7  3

In [16]:
A.shape[1]

2

In [17]:
A[1][1]

3

In [18]:
A=np.array([1,2])

In [19]:
A

array([1, 2])

In [20]:
A.shape

(2,)

In [21]:
Satır_Vektor=np.array([1,2,3,34,2])

In [22]:
u=np.array([1,2]);v=np.array([1,-3])
w=np.array([-1,-2])

In [23]:
u =np.array( [1, 2, 3] )

In [24]:
v=  np.array( [2,1,2] )

In [25]:
u.dot(v)

10

In [26]:
u.view

<function ndarray.view>

In [27]:
u+v #matris toplama

array([3, 3, 5])

In [28]:
u=np.array([1,2]);v=np.array([2,1])
w=u+v;w

array([3, 3])

In [29]:
def doğru_parçası(c,u,v):
       return c*u + (1 - c)*v

In [30]:
c=0
doğru_parçası(c,u,v)

array([2, 1])

In [31]:
c=1
doğru_parçası(c,u,v)

array([1, 2])

In [32]:
c=0.5
doğru_parçası(c,u,v)

array([1.5, 1.5])

In [33]:
# Tranpozu, Devrik

In [34]:
A=np.array([[a00,a01],[a10,a11],[a20,a21]])

In [35]:
A

array([[1, 0],
       [7, 3],
       [7, 3]])

In [36]:
A.T

array([[1, 7, 7],
       [0, 3, 3]])

In [37]:
A.transpose().shape

(2, 3)

In [38]:
A.shape

(3, 2)

In [39]:
A.T.T

array([[1, 0],
       [7, 3],
       [7, 3]])

In [40]:
A=np.array([[1,1,2],[2,1,3]])
B=np.array([[1,1],[2,3],[1,2]])
A.dot(B)

array([[ 5,  8],
       [ 7, 11]])

In [41]:
def vektörel_çarpım(A,B):
    return A.dot(B)

In [42]:
A=np.array([[3],[4]]);B=np.array([[1, 2]]);

In [43]:
vektörel_çarpım(A,B)

array([[3, 6],
       [4, 8]])

In [44]:
vektörel_çarpım(B,A)

 # LEBG

array([[11]])

![image.png](attachment:image.png)

In [45]:
A=np.array([[1,2],[3,4]]);B=np.array([[1,1],[0,1],[1,2]]);

In [47]:
vektörel_çarpım(A,B) # Vektörel çarpımda ilk matrisin sütün sayısı ile ikinci matrisin satır sayısı aynı olmalı

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [49]:
vektörel_çarpım(B,A)

array([[ 4,  6],
       [ 3,  4],
       [ 7, 10]])

In [50]:
PremiumUnleaded=np.array([3/4,1/4])
RegularUnleaded=np.array([2/3,1/3])
RegularLeaded=np.array([1/4,3/4])

In [51]:
mainTable=np.array([PremiumUnleaded,RegularUnleaded,RegularLeaded])

In [52]:
mainDataFrame=pd.DataFrame(mainTable,columns=("crude1","crude2"))

In [53]:
mainDataFrame.index=["PremiumUnleaded","RegularUnleaded","RegularLeaded"]

In [54]:
mainDataFrame

crude1    crude2
PremiumUnleaded  0.750000  0.250000
RegularUnleaded  0.666667  0.333333
RegularLeaded    0.250000  0.750000

In [55]:
Stock=np.array([10,6,5])

In [56]:
vektörel_çarpım(Stock,mainDataFrame)

array([12.75,  8.25])

In [57]:
# Kural 1 Satır

In [58]:
A=np.array([[1,1,2],[2,1,3]]);B=np.array([[1,1],[2,3],[1,2]])

In [59]:
A[1]

array([2, 1, 3])

In [60]:
vektörel_çarpım(A,B)

array([[ 5,  8],
       [ 7, 11]])

In [61]:
vektörel_çarpım(A,B)[0]

array([5, 8])

In [62]:
vektörel_çarpım(A[0],B)

array([5, 8])

In [63]:
# Kural 2 Sütün

In [64]:
vektörel_çarpım(A,B[:,0])

array([5, 7])

In [65]:
vektörel_çarpım(A,B)[:,0]

array([5, 7])

In [66]:
# Geçişkenlik Kuralı

In [67]:
A=np.array([1,2]) ; B=np.array([[2,3],[4,5]]);C=np.array([[2],[1]])

In [68]:
A

array([1, 2])

In [69]:
B

array([[2, 3],
       [4, 5]])

In [70]:
C

array([[2],
       [1]])

In [71]:
vektörel_çarpım(vektörel_çarpım(A,B),C)

array([33])

In [72]:
vektörel_çarpım(A,vektörel_çarpım(B,C))

array([33])

In [73]:
vektörel_çarpım(vektörel_çarpım(A,B),C)==vektörel_çarpım(A,vektörel_çarpım(B,C))

array([ True])

## Problemler



### 1. Problem

In [74]:

A=np.array([[1,2,3],[4,5,6],[7,8,9]]);B=np.array([[1,2],[0,-1],[1,2]])

In [91]:

print("A :\n", A,"\n")



A :
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [92]:
print("B :\n", B,"\n")


B :
 [[ 1  2]
 [ 0 -1]
 [ 1  2]] 



In [93]:
 
print("-A :\n", A*-1,"\n")



-A :
 [[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]] 



In [94]:
print("3A :\n", A*3,"\n")


3A :
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]] 



In [106]:

print("A+2B : \n",A+2*B)


ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [96]:

print("A transpose : \n" , A.T  )


A transpose : 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [98]:
      
print("B transpose : \n" , B.T  )

B transpose : 
 [[ 1  0  1]
 [ 2 -1  2]]


In [99]:
print("AB transpose : \n" , A.dot(B)  )

AB transpose : 
 [[ 4  6]
 [10 15]
 [16 24]]


In [100]:
print("BA transpose : \n" , B.dot(A)  )

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

### 2. Problem

In [123]:
Bira1=[.5,.3,.2]
Bira2=[0,.7,.3]
Bira3=[.1,.3,.6]
Bira_dict={"Bira1":Bira1
          ,"Bira2":Bira2,
          "Bira3":Bira3}

In [124]:
Bira_df=pd.DataFrame(Bira_dict,index=["Bira1","Bira2","Bira3"])

In [125]:
Bira_df

Bira1  Bira2  Bira3
Bira1    0.5    0.0    0.1
Bira2    0.3    0.7    0.3
Bira3    0.2    0.3    0.6

In [126]:
x1=pd.DataFrame({"t1":[0,10,90]},index=["Bira1","Bira2","Bira3"])

In [127]:
x1

t1
Bira1   0
Bira2  10
Bira3  90

In [132]:
Bira_df.shape

(3, 3)

In [131]:
x1.shape

(3, 1)

In [129]:
y1=Bira_df.dot(x1)

In [130]:
y1

t1
Bira1   9.0
Bira2  34.0
Bira3  57.0

### 3.Problem

In [135]:
A=np.array([1,2]) ; B=np.array([[2,3],[4,5]]);C=np.array([[2],[1]])
vektörel_çarpım(vektörel_çarpım(A,B),C)==vektörel_çarpım(A,vektörel_çarpım(B,C))

array([ True])

### 4.Problem

In [140]:
A=np.array([1,2]) ; B=np.array([[2,3],[4,5]])
print(" (AB)T :\n", vektörel_çarpım(A,B).T)
print(" BT*AT :\n",vektörel_çarpım(B.T,A.T))
vektörel_çarpım(A,B).T==vektörel_çarpım(B.T,A.T)

 (AB)T :
 [10 13]
 BT*AT :
 [10 13]


array([ True,  True])

### 5.Problem

In [146]:
A=np.array([[1,2],[2,1]]);
print(" A : \n",A)
print(" A.T : \n",A.T)

print(" A==A.T : \n",A==A.T  )

 A : 
 [[1 2]
 [2 1]]
 A.T : 
 [[1 2]
 [2 1]]
 A==A.T : 
 [[ True  True]
 [ True  True]]


In [148]:
# a 
print("A*A.T simetrik \n" , A.dot(A.T)==A.dot(A.T).T)

A*A.T
 [[ True  True]
 [ True  True]]


In [149]:
# b 
print("A+A.T simetrik \n" , (A+A.T)==(A+A.T).T)

A+A.T simetrik 
 [[ True  True]
 [ True  True]]


### 6.Problem

In [150]:
A=np.array([[1,1],[1,1]]);
B=np.array([[2,1],[1,2]]);

In [151]:
A.shape

(2, 2)

In [152]:
B.shape

(2, 2)

In [158]:
n=A.shape[0]

In [159]:
n**3 # Gereken çarpma sayısı

8

In [160]:
n**3-n**2 # Gereken toplama sayısı

4

### 7.Problem

In [186]:
def matriks_izi(A):
    return np.array([A[i][i] for i in range(len(A))])

In [187]:
# a
matriks_izi(A+B)==(matriks_izi(A)+matriks_izi(B))

array([ True,  True])

In [190]:
# b
matriks_izi(vektörel_çarpım(A,B))  == matriks_izi(vektörel_çarpım(B,A))

array([ True,  True])

## Lineer Denklemlerin Matrisleri

In [199]:
a11=None;a12=None;a13=None;a21=None;a22=None;a23=None; a31=None;a32=None;a33=None;

A=np.array([[a11,a12,a13],
[a21,a22,a23],
[a31,a32,a33]])


In [200]:
A

array([[None, None, None],
       [None, None, None],
       [None, None, None]], dtype=object)

In [202]:
x11=None;x12=None;x13=None;x21=None;x22=None;x23=None; x31=None;x32=None;x33=None;

X=np.array([[x11,x12,x13],
[x21,x22,x23],
[x31,x32,x33]])

In [203]:
b1=None;b2=None;b3=None;
B=np.array([b1,b2,b3])

In [204]:
B

array([None, None, None], dtype=object)

In [206]:
A.dot(X)==B

TypeError: unsupported operand type(s) for *: 'NoneType' and 'NoneType'

<b> X değişken , A ve B sabittir. A*X=B <b>