In [12]:
import pandas as pd
import numpy as np

In [13]:
v1=[1,3]

In [14]:
v2=[2,4]

In [15]:
matrix=[v1,v2]

In [19]:
matrix

[[1, 3], [2, 4]]

In [20]:
np.array(matrix).shape

(2, 2)

In [17]:
pd.DataFrame(np.array(matrix) )

0  1
0  1  3
1  2  4

#  Matris ve Vektör


In [21]:
1 #Scalar

1

In [22]:
[1] # Vektör

[1]

In [23]:
[1,1] # Vektör 1,2

[1, 1]

In [25]:
[[1,1],[1,1]] # Matris 2,2

[[1, 1], [1, 1]]

In [34]:
a00=1;a01=0;a10=7;a11=3;a20=7;a21=3

In [35]:
A=np.array([[a00,a01],[a10,a11],[a20,a21]])

In [39]:
pd.DataFrame(A)

0  1
0  1  0
1  7  3
2  7  3

In [40]:
A.shape[1]

2

In [42]:
A[1][1]

3

In [47]:
A=np.array([1,2])

In [58]:
A

array([1, 2])

In [48]:
A.shape

(2,)

In [50]:
Satır_Vektor=np.array([1,2,3,34,2])

In [55]:
u=np.array([1,2]);v=np.array([1,-3])
w=np.array([-1,-2])

In [60]:
u =np.array( [1, 2, 3] )

In [61]:
v=  np.array( [2,1,2] )

In [67]:
u.dot(v)

10

In [70]:
u.view

<function ndarray.view>

In [74]:
u+v #matris toplama

array([3, 3, 5])

In [82]:
u=np.array([1,2]);v=np.array([2,1])
w=u+v;w

array([3, 3])

In [84]:
def doğru_parçası(c,u,v):
       return c*u + (1 - c)*v

In [85]:
c=0
doğru_parçası(c,u,v)

array([2, 1])

In [86]:
c=1
doğru_parçası(c,u,v)

array([1, 2])

In [87]:
c=0.5
doğru_parçası(c,u,v)

array([1.5, 1.5])

In [90]:
# Tranpozu, Devrik

In [91]:
A=np.array([[a00,a01],[a10,a11],[a20,a21]])

In [92]:
A

array([[1, 0],
       [7, 3],
       [7, 3]])

In [93]:
A.T

array([[1, 7, 7],
       [0, 3, 3]])

In [96]:
A.transpose().shape

(2, 3)

In [97]:
A.shape

(3, 2)

In [98]:
A.T.T

array([[1, 0],
       [7, 3],
       [7, 3]])

In [119]:
A=np.array([[1,1,2],[2,1,3]])
B=np.array([[1,1],[2,3],[1,2]])
A.dot(B)

array([[ 5,  8],
       [ 7, 11]])

In [121]:
def vektörel_çarpım(A,B):
    return A.dot(B)

In [140]:
A=np.array([[3],[4]]);B=np.array([[1, 2]]);

In [142]:
vektörel_çarpım(A,B)

array([[3, 6],
       [4, 8]])

In [ ]:
vektörel_çarpım(B,A)

 # LEBG

![image.png](attachment:image.png)

In [158]:
A=np.array([[1,2],[3,4]]);B=np.array([[1,1],[0,1],[1,2]]);

In [159]:
vektörel_çarpım(A,B) # Vektörel çarpımda ilk matrisin sütün sayısı ile ikinci matrisin satır sayısı aynı olmalı

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [160]:
vektörel_çarpım(B,A)

array([[ 4,  6],
       [ 3,  4],
       [ 7, 10]])

In [175]:
PremiumUnleaded=np.array([3/4,1/4])
RegularUnleaded=np.array([2/3,1/3])
RegularLeaded=np.array([1/4,3/4])

In [176]:
mainTable=np.array([PremiumUnleaded,RegularUnleaded,RegularLeaded])

In [179]:
mainDataFrame=pd.DataFrame(mainTable,columns=("crude1","crude2"))

In [185]:
mainDataFrame.index=["PremiumUnleaded","RegularUnleaded","RegularLeaded"]

In [186]:
mainDataFrame

crude1    crude2
PremiumUnleaded  0.750000  0.250000
RegularUnleaded  0.666667  0.333333
RegularLeaded    0.250000  0.750000

In [173]:
Stock=np.array([10,6,5])

In [183]:
vektörel_çarpım(Stock,mainDataFrame)

array([12.75,  8.25])

In [ ]:
# Kural 1 Satır

In [187]:
A=np.array([[1,1,2],[2,1,3]]);B=np.array([[1,1],[2,3],[1,2]])

In [188]:
A[1]

array([2, 1, 3])

In [192]:
vektörel_çarpım(A,B)

array([[ 5,  8],
       [ 7, 11]])

In [195]:
vektörel_çarpım(A,B)[0]

array([ True,  True])

In [194]:
vektörel_çarpım(A[0],B)

array([5, 8])

In [ ]:
# Kural 2 Sütün

In [244]:
vektörel_çarpım(A,B[:,0])

array([5, 7])

In [243]:
vektörel_çarpım(A,B)[:,0]

array([5, 7])

In [ ]:
# Geçişkenlik Kuralı

In [245]:
A=np.array([1,2]) ; B=np.array([[2,3],[4,5]]);C=np.array([[2],[1]])

In [246]:
A

array([1, 2])

In [247]:
B

array([[2, 3],
       [4, 5]])

In [248]:
C

array([[2],
       [1]])

In [249]:
vektörel_çarpım(vektörel_çarpım(A,B),C)

array([33])

In [250]:
vektörel_çarpım(A,vektörel_çarpım(B,C))

array([33])

In [251]:
vektörel_çarpım(vektörel_çarpım(A,B),C)==vektörel_çarpım(A,vektörel_çarpım(B,C))

array([ True])